export const CREATE_TABLE_ITEM = "CREATE_TABLE_ITEM";
export const DELETETE_ITEM = "DELETETE_ITEM";
export const EDIT_ITEM = "EDIT_ITEM";
export const GET_DATA_FROM_LOCALSTORAGE = "GET_DATA_FROM_LOCALSTORAGE";
export const SET_DATA_TO_LOCALSTORAGE = "SET_DATA_TO_LOCALSTORAGE";
export const CHANGE_PAGE_INDEX = "CHANGE_PAGE_INDEX";
